/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dao.IScolarite;
import dao.ScolariteImpl;
import javax.swing.JOptionPane;
import presentation.TableParkingspots;
import metier.entity.*;
import org.mindrot.jbcrypt.BCrypt;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import static presentation.Login_frame.idextract;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import dao.Connexion;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author lenovo
 */
public class Reservation_List extends javax.swing.JFrame {
    IScolarite action=new ScolariteImpl();
    TableReservation me=new TableReservation();
    Connection conn = null;
    int selectedid;
    private Reservation selectedReservation;

    /**
     * Creates new form Reservation_List
     */
    public Reservation_List() {
        initComponents();
        me.setReservations(action.getAllReservations());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prix = new javax.swing.JTextField();
        Mod = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Date_Debut = new com.toedter.calendar.JDateChooser();
        Date_Fin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Duree = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrixActionPerformed(evt);
            }
        });
        getContentPane().add(Prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 300, 30));

        Mod.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\OneDrive\\Desktop\\Junk\\Parking\\Icons\\edit (1).png")); // NOI18N
        Mod.setText("Modifier");
        Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModActionPerformed(evt);
            }
        });
        getContentPane().add(Mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 100, 30));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\OneDrive\\Desktop\\Junk\\Parking\\Icons\\Cancel (1).png")); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date Debut :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        Date_Debut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Date_DebutPropertyChange(evt);
            }
        });
        getContentPane().add(Date_Debut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 300, 30));

        Date_Fin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Date_FinMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Date_FinMouseExited(evt);
            }
        });
        Date_Fin.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Date_FinComponentAdded(evt);
            }
        });
        Date_Fin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Date_FinFocusLost(evt);
            }
        });
        Date_Fin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Date_FinPropertyChange(evt);
            }
        });
        getContentPane().add(Date_Fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 300, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date Fin :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Duree :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reservation List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 220, -1));

        Duree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DureeActionPerformed(evt);
            }
        });
        getContentPane().add(Duree, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 300, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Prix :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jTable2.setModel(me);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 800, 170));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 880, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrixActionPerformed

    private void ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModActionPerformed
        // Retrieve the values from the UI components
        String selectedDate_Debut = formatDate(Date_Debut.getDate());
        String selectedDate_Fin = formatDate(Date_Fin.getDate());
        String selectedDuree = Duree.getText();
        String selectedPrix = Prix.getText();

        // Update the reservation using the selected ID
        action.modifierReservation(selectedDate_Debut, selectedDate_Fin, selectedDuree, selectedPrix, selectedid);

        // Show a success message
        JOptionPane.showMessageDialog(null, "Modification avec succès");

        // Reload the reservation table
        me.setReservations(action.getAllReservations());
        jTable2.setModel(me);
    }//GEN-LAST:event_ModActionPerformed

    private String formatDate(Date date) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        return dateFormat.format(date);
    }     
    
        private void updatePrix() {
    LocalDate dateDebut = Date_Debut.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate dateFin = Date_Fin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

    if (dateDebut != null && dateFin != null) {
        long difference = Duration.between(dateDebut.atStartOfDay(), dateFin.atStartOfDay()).toHours();
        int duree = (int) difference;

        double PrixR = duree * 1.5;
        Prix.setText(Double.toString(PrixR));
        Duree.setText(Double.toString(duree));
    }}
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DureeActionPerformed

    private void Date_FinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Date_FinPropertyChange
                // TODO add your handling code here:
            if ("date".equals(evt.getPropertyName())) {
        updatePrix();
    }
    }//GEN-LAST:event_Date_FinPropertyChange

    private void Date_FinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Date_FinFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_FinFocusLost

    private void Date_FinComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Date_FinComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_FinComponentAdded

    private void Date_FinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Date_FinMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_FinMouseExited

    private void Date_FinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Date_FinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_FinMouseClicked

    private void Date_DebutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Date_DebutPropertyChange
                // TODO add your handling code here:
    if ("date".equals(evt.getPropertyName())) {
        updatePrix();
    }
    }//GEN-LAST:event_Date_DebutPropertyChange

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    int ligne = jTable2.getSelectedRow();
    selectedid = Integer.parseInt(String.valueOf(me.getValueAt(ligne, 0)));
    String selectedDate_Debut = String.valueOf(me.getValueAt(ligne, 3));
    String selectedDate_Fin = String.valueOf(me.getValueAt(ligne, 4));
    String selectedDuree = String.valueOf(me.getValueAt(ligne, 5));
    String selectedPrix = String.valueOf(me.getValueAt(ligne, 6));

    // Parse the selected dates
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    try {
        Date dateDebut = dateFormat.parse(selectedDate_Debut);
        Date dateFin = dateFormat.parse(selectedDate_Fin);

        // Set the values in your UI components
        Date_Debut.setDate(dateDebut);
        Date_Fin.setDate(dateFin);
    } catch (ParseException e) {
        e.printStackTrace();
    }

    Duree.setText(selectedDuree);
    Prix.setText(selectedPrix);
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_Debut;
    private com.toedter.calendar.JDateChooser Date_Fin;
    private javax.swing.JTextField Duree;
    private javax.swing.JButton Mod;
    private javax.swing.JTextField Prix;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
